import { AI_METERS_TO_PIXELS } from "../../../ai/registry";

export const GREMLIN_DEATH_ANIM_MS = 1400;
export const FISH_COMBAT_MIN_COOLDOWN_MS = 250;
export const FISH_COMBAT_MAX_COOLDOWN_MS = 12_000;
export const FISH_COMBAT_MAX_LAUNCH_RANGE_PX = 10 * AI_METERS_TO_PIXELS;
export const ENEMY_MELEE_KNOCKBACK_SPEED = 120;
export const ENEMY_MELEE_KNOCKBACK_DURATION_MS = 170;
export const ENEMY_MELEE_KNOCKBACK_RECOVERY_TAIL_MS = 100;
export const AI_TO_AI_COLLISION_MIN_PUSH_PER_STEP = 0.06;
export const AI_TO_AI_COLLISION_MAX_PUSH_PER_STEP = 0.45;
